package com.arphen.dontblink.app;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by swozny on 17.04.18.
 */

public class Symbols {

    public static final String[] SET_BIGRAMS_1 = new String[]{"of the",
            "in the", "to the", "on the", "and the", "to be", "for the", "at the", "it is", "it was", "by the", "with the", "that the", "it 's", "from the", "of a", "in a", "do n't", "as a", "in #", "is a", "with a", "he was", "for a", "will be", "had been", "was a", "one of", "i 'm", "is the", "that 's", "the first", "there is", "has been", "the same", "and a", "would be", "can be", "to a", "into the", "and i", "this is", "if you", "there was", "he had", "i do", "i was", "is not", "to have", "did n't", "on a", "to do", "all the", "was the", "of his", "i think", "they were", "there are", "she was", "they are", "you can", "should be", "may be", "have been", "you know", "you 're", "i 've", "in this", "about the", "but the", "to make", "that it", "of #", "over the", "number of", "he said", "and then", "# per_cent", "and it", "by a", "of this", "that he", "the other", "part of", "have been", "in his", "be a", "the most", "to get", "i have", "there 's", "# and", "but it", "can n't", "'s a", "which is", "she had", "in which", "we have", "the new", "and he", "but i", "able to", "through the", "would have", "the end", "some of", "going to", "i can", "of their", "did not", "the world", "to see", "not be", "i 'll", "that they", "do you", "if the", "as the", "is to", "could be", "to go", "a few", "a new", "was not", "the time", "'ve got", "it would", "as the", "end of", "to take", "the way", "at a", "he 's", "they 're", "and #", "the last", "have to", "and in", "the #", "i mean", "must be", "the government", "between the", "had to", "during the", "of them", "is that", "of these", "when the", "the two", "from a", "i am", "can not", "had a", "we are", "you 've", "you have", "i had", "you are", "the next", "and they", "which the", "there were", "do not", "n't know", "of an", "a good", "in their", "have a", "under the", "it has", "does not", "she said", "was n't", "such a", "and his", "that i", "they had", "a very", "the only", "are not", "into a", "i would", "have to", "be the", "the second", "like a", "we can", "and that", "a lot", "that we", "we 're", "the house", "within the", "'s the", "he is", "i know", "to #", "of its", "you do", "back to", "that there", "of all", "and you", "this was", "and we", "as he", "'s not", "they have", "is n't", "most of", "to say", "use of", "i did", "in an", "and she", "their own", "that a", "have a", "does n't", "of her", "not to", "sort of", "when he", "and to", "it will", "the company", "who had", "that you", "against the", "was to", "of it", "the best", "in fact", "we 've", "to give", "after the", "could n't", "that was", "and that", "what is", "to his", "but he", "that is", "a number", "i could", "is an", "would n't", "likely to", "lot of", "want to", "which was", "out_of the", "the case", "trying to", "# years", "wo n't", "might be", "he would", "kind of", "the main", "up the", "are the", "used to", "was in", "the old", "has a", "the fact", "more than", "to find", "or the", "as an", "when i", "the #s", "is it", "i said", "his own", "to me", "on his", "if it", "that she", "it had", "we were", "the country", "not only", "he could", "if they", "those who", "a small", "the whole", "he has", "fact that", "and there",
            "as it", "which are", "as they", "what i", "is no", "and was", "in her", "when you", "are you", "if i", "and other", "than the", "what 's", "be able", "not a", "he did", "i thought",
            "to keep", "she 's", "with his", "could not", "the national", "of that", "of our", "the following", "many of", "the british", "and is", "as i", "want to", "n't you", "of which",
            "have n't", "a long", "of those", "range of", "across the", "who was", "gon na", "in that", "to come", "in its", "been a", "to use", "if he", "the door", "members of", "n't have",
            "i 'd", "in some", "what you", "is also", "on #", "they can", "that this", "would not", "'ll be", "but they", "you will", "a man", "in_order to", "is in", "# the", "when they",
            "you 'll", "up and", "the day", "form of", "a great", "not the", "a large", "the number", "the rest", "# to", "if we", "in my", "as she", "it does", "they do", "and their", "based on",
            "to help", "per_cent of", "it can", "with an", "she could", "n't it", "by #", "to him", "to know", "and this", "will have", "may have", "like that", "or a", "it may", "the uk", "around the",
            "wanted to", "we 'll", "n't be", "the people", "will not", "you could", "about it", "before the", "did you", "out the", "the man", "that of", "of what", "which he", "is that", "from #", "to look",
            "they would", "for this", "p. #", "# #", "like the", "was no", "we do", "a year", "began to", "the year", "last year", "the local", "n't think", "for #", "because it", "but there", "is now", "side of",
            "the court", "in any", "we had", "what the", "and its", "be used", "you were", "people who", "to put", "'m not", "towards the", "like to", "years ago", "for his", "and so", "n't want", "was an", "the united",
            "because the", "must have", "off the", "the problem", "to an", "to their", "the right", "who are", "the more", "to provide", "of my", "at this", "the city", "and if", "difficult to", "after a",
            "need to", "has to", "the early", "could have", "the work", "as we", "what they", "not have", "a more", "the use", "which had", "this year", "way of", "all of", "this time", "you see", "to work",
            "only a", "the great", "the police", "what was", "up in", "had not", "where the", "to this", "where the", "of your", "were not", "and not", "of any", "seemed to", "prime minister", "for their",
            "at #", "sense of", "be made"};

    public static final String[] SET_BIGRAMS_2 = new String[]{
            "of money",
            "and therefore",
            "there has",
            "only be",
            "size of",
            "from this",
            "has n't",
            "needs to",
            "to join",
            "a problem",
            "the level",
            "referred to",
            "up by",
            "in those",
            "'s own",
            "all over",
            "for each",
            "the doctor",
            "to hold",
            "and from",
            "since the",
            "but what",
            "beyond the",
            "just as",
            "the earth",
            "just the",
            "she felt",
            "a young",
            "so the",
            "and which",
            "it 'll",
            "he knew",
            "to win",
            "about that",
            "about a",
            "which may",
            "for any",
            "the international",
            "the woman",
            "other people",
            "understanding of",
            "is so",
            "she thought",
            "that has",
            "up on",
            "of how",
            "it a",
            "was at",
            "me and",
            "hon. friend",
            "her face",
            "less than",
            "thousands of",
            "to set",
            "some #",
            "nothing to",
            "on one",
            "he took",
            "so i",
            "is going",
            "following the",
            "i believe",
            "the various",
            "the kind",
            "related to",
            "this morning",
            "him a",
            "and as",
            "think i",
            "and those",
            "knowledge of",
            "'ve had",
            "with which",
            "it out",
            "he 'd",
            "# months",
            "dealing with",
            "chairman of",
            "but when",
            "for two",
            "had gone",
            "when he",
            "to speak",
            "the start",
            "or so",
            "the others",
            "i feel",
            "local authorities",
            "at her",
            "in mind",
            "to reduce",
            "her and",
            "with your",
            "he thought",
            "to write",
            "should n't",
            "'d like",
            "for us",
            "are all",
            "me a",
            "are very",
            "can get",
            "next year",
            "was being",
            "middle of",
            "a while",
            "she 's",
            "required to",
            "his first",
            "not yet",
            "use the",
            "you go",
            "that would",
            "'m going",
            "the event",
            "he 'll",
            "attention to",
            "in two",
            "experience of",
            "table #",
            "many people",
            "the bottom",
            "without the",
            "into his",
            "had come",
            "lead to",
            "we know",
            "more of",
            "the american",
            "the answer",
            "the sort",
            "n't got",
            "the opportunity",
            "the importance",
            "to explain",
            "a real",
            "the quality",
            "and would",
            "i like",
            "she knew",
            "oh yes",
            "after #",
            "to establish",
            "of women",
            "ready to",
            "the hon.",
            "the years",
            "to any",
            "to deal",
            "'m sure",
            "that have",
            "the scottish",
            "this one",
            "that their",
            "soviet union",
            "from her",
            "was that",
            "said to",
            "it on",
            "page #",
            "out that",
            "that would",
            "his hand",
            "# to",
            "in scotland",
            "with no",
            "presence of",
            "what about",
            "to sell",
            "the size",
            "down on",
            "first of",
            "and my",
            "to improve",
            "said to",
            "you think",
            "from which",
            "the minister",
            "there would",
            "a general",
            "'d have",
            "people to",
            "close to",
            "at an",
            "so you",
            "i say",
            "shall be",
            "with other",
            "world war",
            "no i",
            "possibility of",
            "know what",
            "'s in",
            "held in",
            "is made",
            "the presence",
            "reason for",
            "six months",
            "to learn",
            "seem to",
            "absence of",
            "the basic",
            "up the",
            "much as",
            "plenty of",
            "this has",
            "chance to",
            "a place",
            "the difference",
            "name of",
            "from an",
            "or something",
            "by their",
            "to offer",
            "the position",
            "a sense",
            "had already",
            "report follows",
            "back into",
            "the surface",
            "in each",
            "video-taped report",
            "caused by",
            "the region",
            "february #",
            "our own",
            "suggests that",
            "# or",
            "the street",
            "that some",
            "this would",
            "than in",
            "set up",
            "only in",
            "for her",
            "now the",
            "the relationship",
            "try to",
            "without a",
            "to protect",
            "find out",
            "the reason",
            "was too",
            "the ball",
            "company 's",
            "the usa",
            "then we",
            "relationship between",
            "the garden",
            "the largest",
            "got the",
            "had taken",
            "on_to the",
            "role in",
            "that these",
            "his life",
            "led to",
            "until the",
            "the front",
            "even in",
            "a better",
            "a look",
            "he also",
            "so_that the",
            "a whole",
            "edge of",
            "of interest",
            "than that",
            "in what",
            "she says",
            "i felt",
            "to turn",
            "about this",
            "also the",
            "said it",
            "the fire",
            "of many",
            "i never",
            "to read",
            "were also",
            "to another",
            "she looked",
            "with my",
            "waiting for",
            "had made",
            "the committee",
            "lots of",
            "are more",
            "kinds of",
            "or other",
            "the office",
            "man 's",
            "may well",
            "you a",
            "'s that",
            "them to",
            "ref no",
            "a much",
            "of water",
            "pair of",
            "date award",
            "could do",
            "the girl",
            "this case",
            "n't go",
            "a local",
            "world 's",
            "says that",
            "the highest",
            "in practice",
            "young people",
            "can also",
            "the summer",
            "is there",
            "of local",
            "that can",
            "where he",
            "is on",
            "the firm",
            "time the",
            "the queen",
            "n't really",
            "the er",
            "oh yeah",
            "the economy",
            "there and",
            "came from",
            "and many",
            "although it",
            "and do",
            "more likely",
            "to increase",
            "is of",
            "the women",
            "appears to",
            "continued to",
            "we all",
            "power of",
            "a car",
            "over to",
            "numbers of",
            "if not",
            "the edge",
            "beginning to",
            "why do",
            "come to",
            "of him",
            "to what",
            "go and",
            "he told",
            "which could",
            "in turn",
            "i told",
            "by this",
            "ai n't",
            "the population",
            "asked to",
            "a range",
            "in time",
            "continue to",
            "local authority",
            "then she",
            "failed to",
            "the death",
            "court of",
            "the effects",
            "forced to",
            "to raise",
            "concept of",
            "a minute",
            "a letter",
            "the four",
            "up to",
            "making a",
            "more than",
            "who would",
            "issue of",
            "a whole",
            "way that",
            "from one",
            "or to",
            "what did",
            "and who",
            "his mother",
            "to follow",
            "my father",
            "# was",
            "to continue",
            "for one",
            "all those",
            "the patient",
            "shown in",
            "now i",
            "how do",
            "the evening",
            "the press",
            "no more",
            "have had",
            "made in",
            "to maintain",
            "n't even",
            "does it",
            "know that",
            "whether it",
            "but with",
            "have had",
            "of god",
            "back and",
            "world of",
            "let me",
            "one 's",
            "# hours",
            "the army",
            "to let",
            "at it",
            "do the",
            "two or",
            "and yet",
            "cos i",
            "very much",
            "this may",
            "well it",
            "the bill",
            "choice of",
            "'s very",
            "see pp.",
            "responsibility for",
            "the service",
            "was #",
            "be on",
            "the actual",
            "very well",
            "a word",
            "men and",
            "one in",
            "time i",
            "many years",
            "and others",
            "approach to",
            "effect on",
            "country 's",
            "to spend",
            "between them",
            "as being",
            "perhaps the",
            "give you",
            "one thing",
            "is just",
            "august #",
            "in recent",
            "i remember",
            "this country",
            "only to",
            "was born",
            "will take",
            "found that",
            "a job",
            "support for",
            "similar to",
            "of view",
            "ways of",
            "advantage of",
            "so we",
            "# that",
            "the poor",
            "in chapter",
            "that were",
            "and went",
            "saying that",
            "he might",
            "having to",
            "the site",
            "he asked",
            "down at",
            "the lower",
            "not going",
            "that will",
            "seen as",
            "is used",
            "there had",
            "the london",
            "the wrong",
            "a national",
            "my mother",
            "the wind",
            "few years",
            "on saturday",
            "his hands",
            "of different",
            "a simple",
            "problem of",
            "he wanted",
            "if this",
            "of british",
            "patients with",
            "other words",
            "to discuss",
            "act of",
            "was now",
            "he saw",
            "until #",
            "one is",
            "given a",
            "out with",
            "half a",
            "the greatest",
            "of three",
            "had become",
            "to reach",
            "of public",
            "the president",
            "to believe",
            "structure of",
            "'s first",
            "the boy",
            "to return",
            "before he",
            "life of",
            "were all",
            "are going",
            "of things",
            "i wanted",
            "with one",
            "by which",
            "the worst",
            "and no",
            "the sound",
            "and erm",
            "because you",
            "'s only",
            "the heart",
            "a period",
            "visit to",
            "different from",
            "the team",
            "using a",
            "about what",
            "he should",
            "needs of",
            "used by",
            "came to",
            "to form",
            "the black",
            "one that",
            "the meeting",
            "provide a",
            "under a",
            "find a",
            "has also",
            "will you",
            "a significant",
            "has become",
            "on may",
            "purpose of",
            "be considered",
            "got ta",
            "the traditional",
            "# by",
            "difference between",
            "the middle",
            "a change",
            "he came",
            "is quite",
            "think you",
            "position of",
            "not necessarily",
            "from that",
            "from its",
            "around #",
            "have already",
            "her father",
            "the east",
            "are available",
            "me that",
            "the evidence",
            "at which",
            "the hotel",
            "left the",
            "ten years",
            "always been",
            "the entire",
            "a month",
            "life and",
            "not even",
            "he must",
            "the health",
            "these two",
            "the context",
            "the front",
            "deal of",
            "time when",
            "what to",
            "# miles",
            "hundreds of",
            "risk of",
            "knew that",
            "you just",
            "p. #",
            "thought it",
            "of human",
            "that an",
            "was given",
            "has no",
            "the the",
            "can have",
            "some people",
            "the term",
            "became a",
            "was always",
            "are often",
            "already been",
            "down in",
            "in june",
            "method of",
            "is for",
            "not always",
            "did the",
            "a chance",
            "to other",
            "the introduction",
            "introduction of",
            "the paper",
            "talk to",
            "the ec",
            "# at",
            "important to",
            "an attempt",
            "is at",
            "the financial",
            "be held",
            "not know",
            "# october",
            "that that",
            "health and",
            "on april",
            "years and",
            "the terms",
            "was more",
            "of government",
            "# days",
            "has already",
            "length of",
            "the thing",
            "chance of",
            "interests of",
            "are they",
            "in january",
            "made the",
            "you got",
            "it as",
            "seen in",
            "male speaker",
            "well you",
            "out by",
            "go to",
            "to obtain",
            "days of",
            "to call",
            "he made",
            "reference to",
            "to cover",
            "the commission",
            "a meeting",
            "never been",
            "# march",
            "how it",
            "believe that",
            "the history",
            "on march",
            "people were",
            "problems of",
            "told him",
            "where they",
            "the scheme",
            "er the",
            "at work",
            "did it",
            "in most",
            "price of",
            "look at",
            "be so",
            "face of",
            "the absence",
            "the bed",
            "think that",
            "that way",
            "aspect of",
            "which a",
            "collection of",
            "work and",
            "'ll get",
            "which she",
            "the view",
            "in september",
            "because we",
            "the purpose",
            "may also",
            "in may",
            "a huge",
            "# is",
            "minister of",
            "did he",
            "those in",
            "local government",
            "relating to",
            "if that",
            "something like",
            "subject of",
            "other side",
            "south africa",
            "then they",
            "something to",
            "people and",
            "'s an",
            "a friend",
            "in april",
            "he felt",
            "an example",
            "a common",
            "not all",
            "inside the",
            "to identify",
            "the light",
            "a kind",
            "at night",
            "a case",
            "the rate",
            "are no",
            "examples of",
            "is available",
            "so what",
            "willing to",
            "you like",
            "be of",
            "and one",
            "a book",
            "the corner",
            "the contract",
            "what happened",
            "wish to",
            "of whom",
            "the human",
            "onto the",
            "was quite",
            "the phone",
            "know how",
            "are likely",
            "in october",
            "half the",
            "the order",
            "er i",
            "at their",
            "see that",
            "a piece",
            "just as",
            "living in",
            "and your",
            "a nice",
            "a clear",
            "here is",
            "i i",
            "available to",
            "in france",
            "something that",
            "but is",
            "the open",
            "the usual",
            "she went",
            "think we",
            "context of",
            "is always",
            "four years",
            "right hon.",
            "as many",
            "but as",
            "things that",
            "the programme",
            "impossible to",
            "about his",
            "combination of",
            "refused to",
            "people have",
            "the biggest",
            "the ability",
            "what would",
            "at its",
            "which you",
            "cause of",
            "but his",
            "i might",
            "of thing",
            "who will",
            "'m sorry",
            "these were",
            "in march",
            "have seen",
            "oct. #",
            "jan. #",
            "the concept",
            "had an",
            "we may",
            "how they",
            "they say",
            "this point",
            "back on",
            "the range",
            "had to",
            "the sale",
            "they might",
            "this can",
            "years later",
            "england and",
            "line of",
            "he and",
            "made a",
            "n't been",
            "into account",
            "there may",
            "keep the",
            "this chapter",
            "we want",
            "county council",
            "the things",
            "i found",
            "hon. gentleman",
            "the average",
            "the economic",
            "£# for",
            "every day",
            "is usually",
            "that 's",
            "to £#",
            "does the",
            "a question",
            "# april",
            "they want",
            "work in",
            "n't he",
            "but for",
            "their way",
            "at me",
            "father 's",
            "education and",
            "his way",
            "made it",
            "on june",
            "to feel",
            "he got",
            "the life",
            "the news",
            "was found",
            "or #",
            "the common",
            "decision to",
            "go on",
            "be to",
            "had done",
            "to save",
            "he added",
            "n't say",
            "are two",
            "managed to",
            "available for",
            "because she",
            "that many",
            "the white",
            "president of",
            "they must",
            "was taken",
            "of london",
            "and get",
            "pattern of",
            "the courts",
            "on and",
            "do this",
            "a set",
            "it comes",
            "they all",
            "a company",
            "find the",
            "to break",
            "growth of",
            "or three",
            "the product",
            "#s and",
            "today 's",
            "# when",
            "but now",
            "so you",
            "who can",
            "creation of",
            "information about",
            "provided by",
            "in july",
            "do we",
            "the large",
            "or less",
            "response to",
            "depends on",
            "go on",
            "on our",
            "next week",
            "the research",
            "the structure",
            "took place",
            "and make",
            "and women",
            "same as",
            "used as",
            "the rules",
            "death of",
            "for what",
            "'s why",
            "his voice",
            "not really",
            "existence of",
            "due to",
            "it from",
            "with two",
            "the chance",
            "were still",
            "the creation",
            "the risk",
            "both of",
            "same way",
            "the existing",
            "to eat",
            "they 'd",
            "get it",
            "recent years",
            "where they",
            "and made",
            "i asked",
            "cope with",
            "day of",
            "on with",
            "the sense",
            "early #s",
            "the data",
            "were made",
            "here and",
            "demand for",
            "called the",
            "against a",
            "reasons for",
            "people of",
            "try and",
            "appeared to",
            "attempts to",
            "the island",
            "a house",
            "him to",
            "gave a",
            "the fourth",
            "'s work",
            "the hospital",
            "of children",
            "provision of",
            "a report",
            "he turned",
            "# june",
            "at all",
            "a point",
            "have done",
            "the film",
            "the picture",
            "we got",
            "sept. #",
            "in december",
            "the computer",
            "wide range",
            "god 's",
            "had seen",
            "last time",
            "terms of",
            "university of",
            "her in",
            "them with",
            "as_well_as the",
            "half of",
            "are we",
            "hong kong",
            "for my",
            "made to",
            "my hon.",
            "on to",
            "that when",
            "give the",
            "mother 's",
            "be said",
            "this kind",
            "for our",
            "interest rates",
            "is necessary",
            "started to",
            "where he",
            "it were",
            "by one",
            "the society",
            "# january",
            "in november",
            "the good",
            "the week",
            "a part",
            "put it",
            "the industry",
            "aware that",
            "the upper",
            "total of",
            "government and",
            "to cut",
            "the language",
            "before they",
            "the overall",
            "social and",
            "three months",
            "a system",
            "to act",
            "nov. #",
            "was his",
            "my life",
            "she 'd",
            "the date",
            "why the",
            "think that",
            "to decide",
            "few days",
            "nineteenth century",
            "after that",
            "has had",
            "into her",
            "start of",
            "it the",
            "on oct.",
            "the german",
            "the music",
            "but was",
            "go back",
            "of political",
            "take place",
            "they 'd",
            "the balance",
            "had had",
            "of power",
            "but only",
            "the parties",
            "great deal",
            "this book",
            "can make",
            "tell me",
            "made of",
            "the opposition",
            "quarter of",
            "a bad",
            "is difficult",
            "young man",
            "give a",
            "talking to",
            "the opening",
            "to stand",
            "the scene",
            "# may",
            "and looked",
            "power to",
            "return to",
            "close to",
            "see what",
            "the task",
            "and may",
            "to visit",
            "dec. #",
            "would never",
            "no. #",
            "or more",
            "the list",
            "the type",
            "at some",
            "information on",
            "in every",
            "regarded as",
            "a family",
            "council of",
            "and only",
            "a pair",
            "impact of",
            "the post",
            "well that",
            "been able",
            "evidence that",
            "know that",
            "picture of",
            "talk about",
            "before you",
            "n't we",
            "unlikely to",
            "is based",
            "a fine",
            "more important",
            "to control",
            "we went",
            "on july",
            "or by",
            "the application",
            "whole of",
            "to sit",
            "intended to",
            "n't believe",
            "is known",
            "making the",
            "dealt with",
            "how can",
            "as follows",
            "sent to",
            "forward to",
            "i get",
            "a statement",
            "to send",
            "is he",
            "the capital",
            "results of",
            "the existence",
            "was able",
            "when i",
            "heart of",
            "oh no",
            "by its",
            "copy of",
            "her hand",
            "just to",
            "have an",
            "that any",
            "# september",
            "the plaintiff",
            "too many",
            "up there",
            "due_to the",
            "included in",
            "to draw",
            "'ve done",
            "the letter",
            "the title",
            "on what",
            "problem is",
            "make sure",
            "on all",
            "time he",
            "for three",
            "of education",
            "is #",
            "the shop",
            "was all",
            "of britain",
            "'ve never",
            "do they",
            "let us",
            "groups of",
            "he wrote",
            "said i",
            "in both",
            "new zealand",
            "tell me",
            "will make",
            "to encourage",
            "production of",
            "you say",
            "him with",
            "is clear",
            "in new",
            "point in",
            "and could",
            "sign of",
            "the crown",
            "the western",
            "where it",
            "house in",
            "the sky",
            "the normal",
            "know it",
            "the forest",
            "'s most",
            "below the",
            "in february",
            "taking the",
            "the library",
            "that such",
            "day and",
            "the different",
            "the remaining",
            "thought to",
            "again and",
            "back at",
            "believe that",
            "the property",
            "not for",
            "still be",
            "the streets",
            "the media",
            "many other",
            "and see",
            "child 's",
            "even a",
            "an early",
            "and down",
            "sound of",
            "got a",
            "now and",
            "on them",
            "is required",
            "the grounds",
            "house and",
            "you have",
            "then there",
            "be expected",
            "during a",
            "she asked",
            "all i",
            "on in",
            "an increase",
            "that people",
            "says it",
            "his mind",
            "her a",
            "being the",
            "the growth",
            "better than",
            "so much",
            "theory of",
            "we 'd",
            "his name",
            "is expected",
            "life in",
            "one hand",
            "and took",
            "he found",
            "why not",
            "to watch",
            "has an",
            "something of",
            "the defendant",
            "a public",
            "state for",
            "the bar",
            "the production",
            "think the",
            "a former",
            "it into",
            "see the",
            "the above",
            "#th century",
            "them all",
            "the impact",
            "two weeks",
            "on nov.",
            "on sept.",
            "so it",
            "the season",
            "on jan.",
            "three of",
            "in with",
            "two hundred",
            "the private",
            "contact with",
            "the hall",
            "was held",
            "work is",
            "and did",
            "the policy",
            "pay for",
            "this means",
            "the initial",
            "the trade",
            "er er",
            "most people",
            "one can",
            "was there",
            "were no",
            "king 's",
            "told the",
            "published in",
            "be that",
            "i wo",
            "the northern",
            "a complete",
            "that her",
            "'ll go",
            "leader of",
            "one side",
            "the needs",
            "person who",
            "and be",
            "economic and",
            "i really",
            "per_cent in",
            "to include",
            "'s face",
            "led by",
            "the union",
            "been given",
            "why did",
            "see it",
            "is true",
            "the management",
            "and perhaps",
            "him the",
            "no #",
            "was like",
            "over and",
            "used to",
            "but er",
            "the many",
            "where you",
            "of art",
            "these days",
            "the loss",
            "year and",
            "the action",
            "higher education",
            "take the",
            "you for",
            "you said",
            "still in",
            "to prove",
            "reduce the",
            "the design",
            "meet the",
            "returned to",
            "to open",
            "is probably",
            "she saw",
            "and thus",
            "bottom of",
            "know the",
            "the interests",
            "the staff",
            "n't need",
            "are so",
            "half of",
            "how long",
            "meeting of",
            "feb. #",
            "sale of",
            "work on",
            "i used",
            "will need",
            "with us",
            "and political",
            "had said",
            "the west",
            "think it",
            "member for",
            "the far",
            "the legal",
            "by her",
            "head and",
            "no way",
            "was never",
            "at school",
            "attached to",
            "the baby",
            "a greater",
            "do i",
            "is something",
            "to determine",
            "yeah i",
            "a party",
            "so if",
            "aimed at",
            "a copy",
            "to wait",
            "why i",
            "a separate",
            "needed to",
            "they also",
            "said that",
            "we might",
            "at £#",
            "a list",
            "so we",
            "available in",
            "by some",
            "'s your",
            "the appropriate",
            "for more",
            "out there",
            "see how",
            "an end",
            "replaced by",
            "supported by",
            "into an",
            "the un",
            "working in",
            "because there",
            "though the",
            "in for",
            "since it",
            "view that",
            "you do",
            "out at",
            "might not",
            "the chief",
            "him for",
            "or more",
            "are many",
            "he gave",
            "the food",
            "has made",
            "not an",
            "doing it",
            "do it",
            "is given",
            "the left",
            "what had",
            "on dec.",
            "but to",
            "just one",
            "was already",
            "the principle",
            "also been",
            "the hands",
            "up his",
            "it took",
            "off to",
            "can take",
            "bank of",
            "change of",
            "she does",
            "become a",
            "up from",
            "whether they",
            "for years",
            "and these",
            "had left",
            "the lack",
            "$# million",
            "can we",
            "'s death",
            "the provision",
            "wish to",
            "came back",
            "commitment to",
            "of men",
            "that and",
            "to london",
            "feature of",
            "in different",
            "all his",
            "how you",
            "that could",
            "do is",
            "the individual",
            "were being",
            "for such",
            "on the",
            "well be",
            "aug. #",
            "get a",
            "he may",
            "the relevant",
            "the text",
            "where it",
            "# a",
            "right of",
            "to bed",
            "the organisation",
            "# november",
            "a state",
            "and another",
            "comes to",
            "two days",
            "and three",
            "of appeal",
            "so they",
            "the prince",
            "to enter",
            "failure to",
            "have an",
            "having been",
            "in #-;#",
            "the association",
            "no doubt",
            "# december",
            "to these",
            "before i",
            "distribution of",
            "picked up",
            "much to",
            "thing is",
            "the conservative",
            "you look",
            "a sort",
            "mean that",
            "the natural",
            "to cope",
            "share of",
            "his mouth",
            "this and",
            "section of",
            "to work",
            "sorts of",
            "the recent",
            "and again",
            "n't a",
            "of scotland",
            "you in",
            "old man",
            "she wanted",
            "and development",
            "emphasis on",
            "extent of",
            "not want",
            "of land",
            "the author",
            "as his",
            "to receive",
            "in another",
            "her mind",
            "it down",
            "to remember",
            "a quarter",
            "far more",
            "the client",
            "very different",
            "would make",
            "'s #",
            "became the",
            "food and",
            "is too",
            "the teacher",
            "reduction in",
            "the train",
            "to apply",
            "was then",
            "and after",
            "a private",
            "for these",
            "looked up",
            "reason why",
            "the change",
            "very little",
            "in august",
            "which to",
            "go out",
            "of europe",
            "are made",
            "than it",
            "you the"
    };

    public static final Set<String> bigrams_1 = new HashSet<String>(Arrays.asList(SET_BIGRAMS_1));
    public static final Set<String> bigrams_2 = new HashSet<String>(Arrays.asList(SET_BIGRAMS_2));
    public static final Set<String> bigrams_3 = new HashSet<String>(Arrays.asList(Symbolsone.SET_BIGRAMS_3));
    public static final String[] SET_TRIGRAMS_1 = new String[]{
            "one of the",
            "the end of",
            "part of the",
            "some of the",
            "a number of",
            "there is a",
            "a lot of",
            "there was a",
            "end of the",
            "be able to",
            "it was a",
            "the fact that",
            "to be a",
            "there is no",
            "at the end",
            "it would be",
            "it is not",
            "the number of",
            "it is a",
            "the use of",
            "the rest of",
            "most of the",
            "there was no",
            "at the time",
            "in the first",
            "at the same",
            "members of the",
            "as a result",
            "it was the",
            "the first time",
            "that it is",
            "the same time",
            "on the other",
            "that it was",
            "for the first",
            "can not be",
            "a couple of",
            "would have been",
            "to be the",
            "this is a",
            "in the same",
            "and it was",
            "side of the",
            "to have a",
            "this is the",
            "in which the",
            "back to the",
            "and it is",
            "the united states",
            "it is the",
            "but it was",
            "and in the",
            "but it is",
            "many of the",
            "of the world",
            "that he was",
            "a series of",
            "it will be",
            "is to be",
            "the development of",
            "going to be",
            "in the world",
            "to do with",
            "to have been",
            "of the most",
            "likely to be",
            "i think it",
            "a result of",
            "the case of",
            "it was not",
            "had to be",
            "the other hand",
            "it may be",
            "it has been",
            "rest of the",
            "in the case",
            "is one of",
            "he had been",
            "to make a",
            "that there is",
            "at the moment",
            "as far as",
            "that he had",
            "read in studio",
            "secretary of state",
            "a bit of",
            "is that the",
            "in the uk",
            "member of the",
            "what do you",
            "as part of",
            "the nature of",
            "he was a",
            "you have to",
            "in the early",
            "i want to",
            "of the new",
            "the time of",
            "the basis of",
            "has to be",
            "per_cent of the",
            "the back of",
            "do you think",
            "a matter of",
            "have to be",
            "the form of",
            "the idea of",
            "a variety of",
            "it can be",
            "the top of",
            "to ensure that",
            "is likely to",
            "it had been",
            "in the last",
            "the cost of",
            "the beginning of",
            "you want to",
            "the need for",
            "to go to",
            "was one of",
            "would have to",
            "the prime minister",
            "the house of",
            "was going to",
            "would like to",
            "there will be",
            "parts of the",
            "the secretary of",
            "if you are",
            "was to be",
            "a member of",
            "much of the",
            "in the past",
            "of the first",
            "it should be",
            "the middle of",
            "to make the",
            "is not a",
            "of the year",
            "to do so",
            "the role of",
            "this is not",
            "video-taped report follows",
            "would be a",
            "was in the",
            "the age of",
            "will have to",
            "from # to",
            "in the middle",
            "the united kingdom",
            "part of a",
            "in the morning",
            "the effect of",
            "nature of the",
            "the amount of",
            "to see the",
            "by the time",
            "to look at",
            "the centre of",
            "do you want",
            "to say that",
            "a long time",
            "the importance of",
            "that they are",
            "that there was",
            "as a whole",
            "all the time",
            "the work of",
            "will not be",
            "a group of",
            "as much as",
            "on the basis",
            "the level of",
            "for a moment",
            "by the end",
            "to deal with",
            "the value of",
            "more than a",
            "one of them",
            "he did not",
            "between the two",
            "way in which",
            "seems to be",
            "the sort of",
            "the presence of",
            "i think i",
            "and that the",
            "would not be",
            "it is possible",
            "must have been",
            "a range of",
            "and there was",
            "should not be",
            "of the day",
            "to do it",
            "the most important",
            "the soviet union",
            "I'll have to",
            "use of the",
            "that of the",
            "in the united",
            "if you do",
            "the kind of",
            "of the house",
            "it must be",
            "have to be",
            "if you have",
            "to be able",
            "of the country",
            "and he was",
            "based on the",
            "the labour party",
            "the course of",
            "the question of",
            "wo n't be",
            "the need to",
            "i had to",
            "the possibility of",
            "top of the",
            "if it is",
            "and i think",
            "the majority of",
            "in other words",
            "one or two",
            "at a time",
            "that they were",
            "i do not",
            "the size of",
            "there has been",
            "not to be",
            "has been a",
            "the name of",
            "in the end",
            "seemed to be",
            "the process of",
            "she had been",
            "in the house",
            "of the two",
            "down to the",
            "in the second",
            "it could be",
            "do you know",
            "up in the",
            "in this case",
            "the department of",
            "in this way",
            "is in the",
            "it is important",
            "who had been",
            "in the way",
            "it is also",
            "is not the",
            "in the form",
            "if you want",
            "may not be",
            "any of the",
            "we have to",
            "will be a",
            "he's going to",
            "she's going to",
            "the absence of",
            "to get the",
            "think it's",
            "had been a",
            "i 'm sorry",
            "the quality of",
            "the effects of",
            "n't have to",
            "of all the",
            "to be in",
            "are to be",
            "i have to",
            "that it would",
            "the other side",
            "are likely to",
            "point of view",
            "may have been",
            "can be used",
            "of the same",
            "the result of",
            "the company 's",
            "the right to",
            "that 's why",
            "the same way",
            "which had been",
            "do n't like",
            "in a way",
            "out in the",
            "used to be",
            "be used to",
            "the way in",
            "to be made",
            "the introduction of",
            "that 's all",
            "in the next",
            "there would be",
            "i 'd like",
            "that there are",
            "one of those",
            "was the first",
            "he had a",
            "all over the",
            "did n't want",
            "fact that the",
            "wide range of",
            "it in the",
            "the subject of",
            "had not been",
            "it would have",
            "chairman of the",
            "it does not",
            "at the top",
            "there had been",
            "and i was",
            "a great deal",
            "needs to be",
            "the history of",
            "in such a",
            "i think we",
            "to find out",
            "two or three",
            "of a new",
            "in the #",
            "they 've got",
            "as it is",
            "the whole of",
            "but there is",
            "it 's all",
            "been able to",
            "a kind of",
            "there is an",
            "aware of the",
            "of the national",
            "on june #",
            "the same as",
            "of the company",
            "have n't got",
            "seems to have",
            "they are not",
            "they 're not",
            "when i was",
            "was able to",
            "could not be",
            "my hon. friend",
            "a piece of",
            "if you can",
            "is going to",
            "the creation of",
            "the face of",
            "what 's the",
            "the start of",
            "might have been",
            "i 'll be",
            "and this is",
            "at that time",
            "i wo n't",
            "will be the",
            "a sense of",
            "result of the",
            "an attempt to",
            "this was the",
            "he 's got",
            "to use the",
            "when he was",
            "'m going to",
            "could have been",
            "on oct. #",
            "one of his",
            "there are no",
            "in the future",
            "and on the",
            "but there was",
            "more likely to",
            "that she had",
            "did n't have",
            "the context of",
            "the existence of",
            "to # per_cent",
            "i used to",
            "on the ground",
            "of the #s",
            "the point of",
            "on the floor",
            "of the british",
            "each of the",
            "for a while",
            "not going to",
            "they did n't",
            "of state for",
            "some of them",
            "is that it",
            "if it 's",
            "a period of",
            "the opportunity to",
            "the purpose of",
            "i think you",
            "need to be",
            "the lack of",
            "i was n't",
            "to take a",
            "great deal of",
            "that he would",
            "on jan. #",
            "it is n't",
            "we need to",
            "by # per_cent",
            "# per_cent in",
            "on july #",
            "but in the",
            "the problem of",
            "in the late",
            "involved in the",
            "have been a",
            "a set of",
            "the court of",
            "in recent years",
            "if there is",
            "the early #s",
            "on sept. #",
            "a wide range",
            "but he was",
            "they do not",
            "for a few",
            "went to the",
            "the side of",
            "a pair of",
            "on nov. #",
            "'re gon na",
            "i 'll have",
            "changes in the",
            "the concept of",
            "go to the",
            "of the other",
            "the relationship between",
            "to get a",
            "edge of the",
            "view of the",
            "one of these",
            "to keep the",
            "he does n't",
            "the interests of",
            "he 's a",
            "he would have",
            "that was the",
            "to make it",
            "middle of the",
            "to try to",
            "place in the",
            "that 's not",
            "at the back",
            "can be seen",
            "of their own",
            "a sort of",
            "in this country",
            "on dec. #",
            "there are two",
            "were to be",
            "the bottom of",
            "there are many",
            "i mean i",
            "the rate of",
            "of the old",
            "of the people",
            "on the way",
            "i had a",
            "the hon. gentleman",
            "of the state",
            "the death of",
            "it did n't",
            "in any case",
            "in one of",
            "be in the",
            "but i 'm",
            "of the time",
            "will be able",
            "'s gon na",
            "the first of",
            "time of the",
            "and at the",
            "and there 's",
            "known as the",
            "the head of",
            "has not been",
            "to be found",
            "head of the",
            "the needs of",
            "and all the",
            "back of the",
            "how do you",
            "on the same",
            "is a very",
            "the heart of",
            "as in the",
            "he had to",
            "was on the",
            "are going to",
            "of his own",
            "and i do",
            "this was a",
            "to be an",
            "you have n't",
            "i would have",
            "that this is",
            "you have a",
            "responsible for the",
            "it was an",
            "you wo n't",
            "if they are",
            "i think the",
            "there were no",
            "what are you",
            "and there are",
            "i am not",
            "sort of thing",
            "out to be",
            "i wanted to",
            "that is the",
            "he was not",
            "for a long",
            "you 're going",
            "part in the",
            "be found in",
            "of # per_cent",
            "there may be",
            "more or less",
            "she could n't",
            "the results of",
            "we have a",
            "which has been",
            "he was n't",
            "of the city",
            "to have the",
            "on feb. #",
            "the #s and",
            "and of the",
            "for the next",
            "you need to",
            "that we have",
            "leader of the",
            "the power of",
            "it 's been",
            "the sound of",
            "it was only",
            "see pp. #-#",
            "in the face",
            "the university of"};

    public static final HashSet<String> trigrams_1 = new HashSet<String>(Arrays.asList(SET_TRIGRAMS_1));
    public static final HashSet<String> trigrams_2 = new HashSet<String>(Arrays.asList(Symbolsone.SET_TRIGRAMS_2));

}
